sudo: required

services:
  - postgresql

addons:
  postgresql: 10

language: php

php:
  - 7.4

before_install:
  - composer self-update

install:
  - composer install --no-interaction --prefer-dist --no-scripts --no-progress --no-suggest --optimize-autoloader --classmap-authoritative

before_script:
  - mv Tests/Configuration/.config.travis.ini Tests/Configuration/.config.local.ini
  - psql -c 'CREATE DATABASE storage;' -U postgres
  - psql -U postgres storage < ./Tests/fixtures/schema.sql

script:
  - vendor/bin/phing ci

after_script:
    - wget https://github.com/satooshi/php-coveralls/releases/download/v1.0.1/coveralls.phar && php coveralls.phar --verbose --config Tests/.coveralls.yml
    - php coveralls.phar --verbose --config Tests/.coveralls.yml

after_failure:
  - for i in $(find Tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done
